### Penjelasan Analisis

**Metode yang digunakan:**
Tuliskan teknik atau algoritma yang diterapkan pada tahap ini.

**Alasan penggunaan:**
Jelaskan alasan pemilihan metode dan relevansinya dengan tujuan proyek.

**Hasil yang didapat:**
Interpretasikan hasil yang diperoleh setelah metode diterapkan.

---

# **Penting**
- Jangan mengubah atau menambahkan cell text yang sudah disediakan, Anda hanya perlu mengerjakan cell code yang sudah disediakan.
- Pastikan seluruh kriteria memiliki output yang sesuai, karena jika tidak ada output dianggap tidak selesai.
- Misal, Anda menggunakan df = df.dropna() silakan gunakan df.isnull().sum() sebagai tanda sudah berhasil. Silakan sesuaikan seluruh output dengan perintah yang sudah disediakan.
- Pastikan Anda melakukan Run All sebelum mengirimkan submission untuk memastikan seluruh cell berjalan dengan baik.
- Pastikan Anda menggunakan variabel df dari awal sampai akhir dan tidak diperbolehkan mengganti nama variabel tersebut.
- Hapus simbol pagar (#) pada kode yang bertipe komentar jika Anda menerapkan kriteria tambahan
- Biarkan simbol pagar (#) jika Anda tidak menerapkan kriteria tambahan
- Pastikan Anda mengerjakan sesuai section yang sudah diberikan tanpa mengubah judul atau header yang disediakan.

# **1. Import Library**
Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning.

In [41]:
# Install library yang diperlukan jika belum ada
!pip install pandas numpy matplotlib seaborn scikit-learn yellowbrick joblib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\program files\python313\lib\site-packages (2.3.1)
Requirement already satisfied: numpy in c:\program files\python313\lib\site-packages (2.3.2)
Requirement already satisfied: matplotlib in c:\program files\python313\lib\site-packages (3.10.5)
Requirement already satisfied: seaborn in c:\program files\python313\lib\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in c:\program files\python313\lib\site-packages (1.7.1)
Requirement already satisfied: yellowbrick in c:\program files\python313\lib\site-packages (1.5)
Requirement already satisfied: joblib in c:\program files\python313\lib\site-packages (1.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\program files\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\program files\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\program files\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\program files\python313\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\program files\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\program files\python313\lib\site-packages (from matplotlib) (4.59.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\program files\python313\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\program files\python313\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\program files\python313\lib\site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\program files\python313\lib\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: scipy>=1.8.0 in c:\program files\python313\lib\site-packages (from scikit-learn) (1.16.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\program files\python313\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in c:\program files\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [42]:
#Type your code here
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.model_selection import GridSearchCV
import joblib
import warnings
warnings.filterwarnings('ignore')

In [43]:
# Load data hasil clustering
df = pd.read_csv('data_clustering_with_target.csv')

In [44]:
# Menampilkan 5 data teratas
df.head()

,TransactionAmount,PreviousTransactionDate,TransactionType,Location,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,TransactionDate,Target
0,-0.973455,-0.792526,0.481412,1.174756,-1.217974,1.418729,-1.329835,-0.545341,-0.203244,0.006538,-0.733855,0
1,0.270666,-0.107231,0.481412,-0.516972,-1.217974,1.306732,-1.329835,0.307479,-0.203244,2.223530,0.104720,3
2,-0.588006,0.008361,0.481412,0.127495,1.189129,-1.437194,1.273185,-0.900683,-0.203244,-1.016452,-1.350738,2
3,-0.388033,-0.602625,0.481412,0.933080,1.189129,-1.045205,1.273185,-1.341307,-0.203244,0.892866,-0.174805,2
4,-0.705290,-0.854450,0.481412,0.530288,-1.217974,-1.493193,1.273185,0.748103,-0.203244,-1.103799,-1.620625,2

In [45]:
# Menampilkan info dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2420 entries, 0 to 2419
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   TransactionAmount        2420 non-null   float64
 1   PreviousTransactionDate  2420 non-null   float64
 2   TransactionType          2420 non-null   float64
 3   Location                 2420 non-null   float64
 4   Channel                  2420 non-null   float64
 5   CustomerAge              2420 non-null   float64
 6   CustomerOccupation       2420 non-null   float64
 7   TransactionDuration      2420 non-null   float64
 8   LoginAttempts            2420 non-null   float64
 9   AccountBalance           2420 non-null   float64
 10  TransactionDate          2420 non-null   float64
 11  Target                   2420 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 227.0 KB

In [46]:
# Menampilkan statistik deskriptif dataset
df.describe()

,TransactionAmount,PreviousTransactionDate,TransactionType,Location,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,TransactionDate,Target
count,2.420000e+03,2.420000e+03,2.420000e+03,2.420000e+03,2.420000e+03,2.420000e+03,2.420000e+03,2.420000e+03,2.420000e+03,2.420000e+03,2.420000e+03,2420.000000
mean,5.872254e-18,4.183981e-17,-4.991416e-17,6.899898e-17,-2.936127e-17,-5.138222e-18,7.266914e-17,-2.936127e-18,-2.055289e-17,1.027644e-17,-1.350618e-16,1.371074
std,1.000207e+00,1.000207e+00,1.000207e+00,1.000207e+00,1.000207e+00,1.000207e+00,1.000207e+00,1.000207e+00,1.000207e+00,1.000207e+00,1.000207e+00,1.154601
min,-1.020966e+00,-1.728269e+00,-1.807421e+00,-1.725349e+00,-1.217974e+00,-1.493193e+00,-1.329835e+00,-1.554512e+00,-2.032439e-01,-1.278259e+00,-1.745929e+00,0.000000
25%,-7.405539e-01,-8.658027e-01,4.814115e-01,-8.392062e-01,-1.217974e+00,-9.892064e-01,-1.329835e+00,-8.011873e-01,-2.032439e-01,-9.227827e-01,-8.591595e-01,0.000000
50%,-2.897467e-01,-3.336174e-03,4.814115e-01,6.657725e-03,-1.442272e-02,1.876644e-02,4.055118e-01,-1.047172e-01,-2.032439e-01,-1.062677e-01,-1.306416e-03,1.000000
75%,3.917374e-01,8.646348e-01,4.814115e-01,8.525217e-01,1.189129e+00,8.027453e-01,1.273185e+00,5.953064e-01,-2.032439e-01,6.557115e-01,8.758243e-01,2.000000
max,5.571004e+00,1.691323e+00,2.770244e+00,1.738665e+00,2.392680e+00,1.978714e+00,2.140859e+00,2.567454e+00,6.628010e+00,2.536099e+00,1.724039e+00,3.000000

In [47]:
# Mengecek missing value dan duplikat
print('Missing value per kolom:')
print(df.isnull().sum())
print('Jumlah duplikat:', df.duplicated().sum())

Missing value per kolom:
TransactionAmount          0
PreviousTransactionDate    0
TransactionType            0
Location                   0
Channel                    0
CustomerAge                0
CustomerOccupation         0
TransactionDuration        0
LoginAttempts              0
AccountBalance             0
TransactionDate            0
Target                     0
dtype: int64
Jumlah duplikat: 22

In [48]:
# Drop kolom ID jika ada
id_cols = ['TransactionID', 'AccountID', 'DeviceID', 'IPAddress', 'MerchantID']
df = df.drop([col for col in id_cols if col in df.columns], axis=1)

In [49]:
# Feature encoding untuk kolom kategorikal
from sklearn.preprocessing import LabelEncoder
categorical_cols = df.select_dtypes(include=['object', 'category']).columns
encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))
    encoders[col] = le

In [50]:
# Feature scaling untuk kolom numerik
from sklearn.preprocessing import MinMaxScaler
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns
scaler = MinMaxScaler()
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

# **2. Memuat Dataset dari Hasil Clustering**
Memuat dataset hasil clustering dari file CSV ke dalam variabel DataFrame.

In [51]:
# Gunakan dataset hasil clustering yang memiliki fitur Target
df = pd.read_csv("data_clustering_with_target.csv")
df['Target'] = df['Target'].round().astype(int)

In [52]:
# Cek tipe dan nilai unik kolom Target setelah load data
print('Unique Target:', df['Target'].unique())
print('Target dtype:', df['Target'].dtype)
print('Target head:', df['Target'].head(10))

Unique Target: [0 3 2 1]
Target dtype: int64
Target head: 0    0
1    3
2    2
3    2
4    2
5    1
6    0
7    1
8    1
9    1
Name: Target, dtype: int64

In [53]:
# Tampilkan 5 baris pertama dengan function head.
print("5 baris pertama dataset:")
print(df.head())
print(f"\nShape dataset: {df.shape}")
print(f"\nKolom dalam dataset: {df.columns.tolist()}")
print(f"\nInfo dataset:")
print(df.info())

5 baris pertama dataset:
   TransactionAmount  PreviousTransactionDate  TransactionType  Location  \
0          -0.973455                -0.792526         0.481412  1.174756
1           0.270666                -0.107231         0.481412 -0.516972
2          -0.588006                 0.008361         0.481412  0.127495
3          -0.388033                -0.602625         0.481412  0.933080
4          -0.705290                -0.854450         0.481412  0.530288

    Channel  CustomerAge  CustomerOccupation  TransactionDuration  \
0 -1.217974     1.418729           -1.329835            -0.545341
1 -1.217974     1.306732           -1.329835             0.307479
2  1.189129    -1.437194            1.273185            -0.900683
3  1.189129    -1.045205            1.273185            -1.341307
4 -1.217974    -1.493193            1.273185             0.748103

   LoginAttempts  AccountBalance  TransactionDate  Target
0      -0.203244        0.006538        -0.733855       0
1      -0.203244        2.223530         0.104720       3
2      -0.203244       -1.016452        -1.350738       2
3      -0.203244        0.892866        -0.174805       2
4      -0.203244       -1.103799        -1.620625       2

Shape dataset: (2420, 12)

Kolom dalam dataset: ['TransactionAmount', 'PreviousTransactionDate', 'TransactionType', 'Location', 'Channel', 'CustomerAge', 'CustomerOccupation', 'TransactionDuration', 'LoginAttempts', 'AccountBalance', 'TransactionDate', 'Target']

Info dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2420 entries, 0 to 2419
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   TransactionAmount        2420 non-null   float64
 1   PreviousTransactionDate  2420 non-null   float64
 2   TransactionType          2420 non-null   float64
 3   Location                 2420 non-null   float64
 4   Channel                  2420 non-null   float64
 5   CustomerAge              2420 non-null   float64
 6   CustomerOccupation       2420 non-null   float64
 7   TransactionDuration      2420 non-null   float64
 8   LoginAttempts            2420 non-null   float64
 9   AccountBalance           2420 non-null   float64
 10  TransactionDate          2420 non-null   float64
 11  Target                   2420 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 227.0 KB
None

# **3. Data Splitting**
Tahap Data Splitting bertujuan untuk memisahkan dataset menjadi dua bagian: data latih (training set) dan data uji (test set).

In [54]:
# Menggunakan train_test_split() untuk melakukan pembagian dataset.
# Memisahkan fitur (X) dan target (y)
X = df.drop('Target', axis=1)
y = df['Target']

print(f"\nDistribusi target:")
print(y.value_counts())

# Pembagian data training dan testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(f"\nUkuran data training: {X_train.shape}")
print(f"Ukuran data testing: {X_test.shape}")

Distribusi target:
Target
0    754
1    590
3    576
2    500
Name: count, dtype: int64

Ukuran data training: (1936, 11)
Ukuran data testing: (484, 11)

# **4. Membangun Model Klasifikasi**
Setelah memilih algoritma klasifikasi yang sesuai, langkah selanjutnya adalah melatih model menggunakan data latih.

Berikut adalah rekomendasi tahapannya.
1. Menggunakan algoritma klasifikasi yaitu Decision Tree.
2. Latih model menggunakan data yang sudah dipisah.

In [55]:
# Buatlah model klasifikasi menggunakan Decision Tree
dt_model = DecisionTreeClassifier(random_state=42)

# Latih model
dt_model.fit(X_train, y_train)

# Prediksi
dt_pred = dt_model.predict(X_test)

# Evaluasi Decision Tree
dt_accuracy = accuracy_score(y_test, dt_pred)
dt_precision = precision_score(y_test, dt_pred, average='weighted')
dt_recall = recall_score(y_test, dt_pred, average='weighted')
dt_f1 = f1_score(y_test, dt_pred, average='weighted')

print("=== EVALUASI DECISION TREE ===")
print(f"Akurasi: {dt_accuracy:.4f}")
print(f"Presisi: {dt_precision:.4f}")
print(f"Recall: {dt_recall:.4f}")
print(f"F1-Score: {dt_f1:.4f}")

=== EVALUASI DECISION TREE ===
Akurasi: 0.9587
Presisi: 0.9592
Recall: 0.9587
F1-Score: 0.9588

In [56]:
# Menyimpan Model
import joblib
joblib.dump(dt_model, 'decision_tree_model.h5')
print("\nModel Decision Tree berhasil disimpan sebagai 'decision_tree_model.h5'")

Model Decision Tree berhasil disimpan sebagai 'decision_tree_model.h5'

# **5. Memenuhi Kriteria Skilled dan Advanced dalam Membangun Model Klasifikasi**

**Biarkan kosong jika tidak menerapkan kriteria skilled atau advanced**

In [57]:
# Melatih model menggunakan algoritma klasifikasi scikit-learn selain Decision Tree.

# 1. Random Forest
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)

rf_accuracy = accuracy_score(y_test, rf_pred)
rf_precision = precision_score(y_test, rf_pred, average='weighted')
rf_recall = recall_score(y_test, rf_pred, average='weighted')
rf_f1 = f1_score(y_test, rf_pred, average='weighted')

# 2. Support Vector Machine
svm_model = SVC(random_state=42)
svm_model.fit(X_train, y_train)
svm_pred = svm_model.predict(X_test)

svm_accuracy = accuracy_score(y_test, svm_pred)
svm_precision = precision_score(y_test, svm_pred, average='weighted')
svm_recall = recall_score(y_test, svm_pred, average='weighted')
svm_f1 = f1_score(y_test, svm_pred, average='weighted')

# 3. K-Nearest Neighbors
knn_model = KNeighborsClassifier()
knn_model.fit(X_train, y_train)
knn_pred = knn_model.predict(X_test)

knn_accuracy = accuracy_score(y_test, knn_pred)
knn_precision = precision_score(y_test, knn_pred, average='weighted')
knn_recall = recall_score(y_test, knn_pred, average='weighted')
knn_f1 = f1_score(y_test, knn_pred, average='weighted')

# 4. Logistic Regression
lr_model = LogisticRegression(random_state=42, max_iter=1000)
lr_model.fit(X_train, y_train)
lr_pred = lr_model.predict(X_test)

lr_accuracy = accuracy_score(y_test, lr_pred)
lr_precision = precision_score(y_test, lr_pred, average='weighted')
lr_recall = recall_score(y_test, lr_pred, average='weighted')
lr_f1 = f1_score(y_test, lr_pred, average='weighted')

In [58]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada seluruh algoritma yang sudah dibuat.
print("\n" + "="*60)
print("PERBANDINGAN PERFORMA SELURUH ALGORITMA")
print("="*60)

models_results = {
    'Decision Tree': [dt_accuracy, dt_precision, dt_recall, dt_f1],
    'Random Forest': [rf_accuracy, rf_precision, rf_recall, rf_f1],
    'SVM': [svm_accuracy, svm_precision, svm_recall, svm_f1],
    'KNN': [knn_accuracy, knn_precision, knn_recall, knn_f1],
    'Logistic Regression': [lr_accuracy, lr_precision, lr_recall, lr_f1]
}

results_df = pd.DataFrame(models_results,
                         index=['Accuracy', 'Precision', 'Recall', 'F1-Score']).T

print(results_df.round(4))

# Mencari model terbaik
best_model_name = results_df['Accuracy'].idxmax()
print(f"\nModel terbaik berdasarkan akurasi: {best_model_name}")
print(f"Akurasi terbaik: {results_df.loc[best_model_name, 'Accuracy']:.4f}")

============================================================
PERBANDINGAN PERFORMA SELURUH ALGORITMA
============================================================
                     Accuracy  Precision  Recall  F1-Score
Decision Tree          0.9587     0.9592  0.9587    0.9588
Random Forest          0.9793     0.9794  0.9793    0.9794
SVM                    0.9360     0.9377  0.9360    0.9363
KNN                    0.8595     0.8595  0.8595    0.8580
Logistic Regression    0.9483     0.9491  0.9483    0.9486

Model terbaik berdasarkan akurasi: Random Forest
Akurasi terbaik: 0.9793

In [59]:
# Menyimpan Model Selain Decision Tree
# Model ini bisa lebih dari satu
import joblib
joblib.dump(rf_model, 'explore_RandomForest_classification.h5')
joblib.dump(svm_model, 'explore_SVM_classification.h5')
joblib.dump(knn_model, 'explore_KNN_classification.h5')
joblib.dump(lr_model, 'explore_LogisticRegression_classification.h5')

print("\nModel-model berhasil disimpan:")
print("- explore_RandomForest_classification.h5")
print("- explore_SVM_classification.h5")
print("- explore_KNN_classification.h5")
print("- explore_LogisticRegression_classification.h5")

Model-model berhasil disimpan:
- explore_RandomForest_classification.h5
- explore_SVM_classification.h5
- explore_KNN_classification.h5
- explore_LogisticRegression_classification.h5

Hyperparameter Tuning Model

Pilih salah satu algoritma yang ingin Anda tuning

In [60]:
# Lakukan Hyperparameter Tuning dan Latih ulang.
# Lakukan dalam satu cell ini saja.

# Hyperparameter tuning untuk Random Forest (model terbaik atau pilihan)
print("\n" + "="*50)
print("HYPERPARAMETER TUNING - RANDOM FOREST")
print("="*50)

# Parameter grid untuk Random Forest
param_grid_rf = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Grid Search
grid_search_rf = GridSearchCV(
    RandomForestClassifier(random_state=42),
    param_grid_rf,
    cv=5,
    scoring='accuracy',
    n_jobs=-1,
    verbose=1
)

# Fitting
grid_search_rf.fit(X_train, y_train)

# Model terbaik hasil tuning
best_rf_model = grid_search_rf.best_estimator_

print(f"\nParameter terbaik: {grid_search_rf.best_params_}")
print(f"Best cross-validation score: {grid_search_rf.best_score_:.4f}")

# Prediksi dengan model yang sudah dituning
tuned_pred = best_rf_model.predict(X_test)

# Evaluasi model hasil tuning
tuned_accuracy = accuracy_score(y_test, tuned_pred)
tuned_precision = precision_score(y_test, tuned_pred, average='weighted')
tuned_recall = recall_score(y_test, tuned_pred, average='weighted')
tuned_f1 = f1_score(y_test, tuned_pred, average='weighted')

==================================================
HYPERPARAMETER TUNING - RANDOM FOREST
==================================================
Fitting 5 folds for each of 108 candidates, totalling 540 fits

Parameter terbaik: {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}
Best cross-validation score: 0.9778

Parameter terbaik: {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}
Best cross-validation score: 0.9778

In [61]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada algoritma yang sudah dituning.
print("\n=== EVALUASI MODEL SETELAH HYPERPARAMETER TUNING ===")
print(f"Akurasi: {tuned_accuracy:.4f}")
print(f"Presisi: {tuned_precision:.4f}")
print(f"Recall: {tuned_recall:.4f}")
print(f"F1-Score: {tuned_f1:.4f}")

# Perbandingan sebelum dan sesudah tuning
print("\n=== PERBANDINGAN SEBELUM DAN SESUDAH TUNING ===")
comparison_df = pd.DataFrame({
    'Sebelum Tuning': [rf_accuracy, rf_precision, rf_recall, rf_f1],
    'Sesudah Tuning': [tuned_accuracy, tuned_precision, tuned_recall, tuned_f1]
}, index=['Accuracy', 'Precision', 'Recall', 'F1-Score'])

print(comparison_df.round(4))

=== EVALUASI MODEL SETELAH HYPERPARAMETER TUNING ===
Akurasi: 0.9793
Presisi: 0.9794
Recall: 0.9793
F1-Score: 0.9794

=== PERBANDINGAN SEBELUM DAN SESUDAH TUNING ===
           Sebelum Tuning  Sesudah Tuning
Accuracy           0.9793          0.9793
Precision          0.9794          0.9794
Recall             0.9793          0.9793
F1-Score           0.9794          0.9794

In [62]:
# Menyimpan Model hasil tuning
import joblib
joblib.dump(best_rf_model, 'tuning_classification.h5')
print("\nModel hasil tuning berhasil disimpan sebagai 'tuning_classification.h5'")

Model hasil tuning berhasil disimpan sebagai 'tuning_classification.h5'

End of Code

## Exploratory Data Analysis (EDA)
Berikut adalah tampilan awal, informasi, dan statistik deskriptif dari dataset yang digunakan.

In [63]:
# Menampilkan 5 baris pertama dataset
df.head()

,TransactionAmount,PreviousTransactionDate,TransactionType,Location,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,TransactionDate,Target
0,-0.973455,-0.792526,0.481412,1.174756,-1.217974,1.418729,-1.329835,-0.545341,-0.203244,0.006538,-0.733855,0
1,0.270666,-0.107231,0.481412,-0.516972,-1.217974,1.306732,-1.329835,0.307479,-0.203244,2.223530,0.104720,3
2,-0.588006,0.008361,0.481412,0.127495,1.189129,-1.437194,1.273185,-0.900683,-0.203244,-1.016452,-1.350738,2
3,-0.388033,-0.602625,0.481412,0.933080,1.189129,-1.045205,1.273185,-1.341307,-0.203244,0.892866,-0.174805,2
4,-0.705290,-0.854450,0.481412,0.530288,-1.217974,-1.493193,1.273185,0.748103,-0.203244,-1.103799,-1.620625,2

In [64]:
# Menampilkan informasi dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2420 entries, 0 to 2419
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   TransactionAmount        2420 non-null   float64
 1   PreviousTransactionDate  2420 non-null   float64
 2   TransactionType          2420 non-null   float64
 3   Location                 2420 non-null   float64
 4   Channel                  2420 non-null   float64
 5   CustomerAge              2420 non-null   float64
 6   CustomerOccupation       2420 non-null   float64
 7   TransactionDuration      2420 non-null   float64
 8   LoginAttempts            2420 non-null   float64
 9   AccountBalance           2420 non-null   float64
 10  TransactionDate          2420 non-null   float64
 11  Target                   2420 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 227.0 KB

In [65]:
# Menampilkan statistik deskriptif dataset
df.describe()

,TransactionAmount,PreviousTransactionDate,TransactionType,Location,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,TransactionDate,Target
count,2.420000e+03,2.420000e+03,2.420000e+03,2.420000e+03,2.420000e+03,2.420000e+03,2.420000e+03,2.420000e+03,2.420000e+03,2.420000e+03,2.420000e+03,2420.000000
mean,5.872254e-18,4.183981e-17,-4.991416e-17,6.899898e-17,-2.936127e-17,-5.138222e-18,7.266914e-17,-2.936127e-18,-2.055289e-17,1.027644e-17,-1.350618e-16,1.371074
std,1.000207e+00,1.000207e+00,1.000207e+00,1.000207e+00,1.000207e+00,1.000207e+00,1.000207e+00,1.000207e+00,1.000207e+00,1.000207e+00,1.000207e+00,1.154601
min,-1.020966e+00,-1.728269e+00,-1.807421e+00,-1.725349e+00,-1.217974e+00,-1.493193e+00,-1.329835e+00,-1.554512e+00,-2.032439e-01,-1.278259e+00,-1.745929e+00,0.000000
25%,-7.405539e-01,-8.658027e-01,4.814115e-01,-8.392062e-01,-1.217974e+00,-9.892064e-01,-1.329835e+00,-8.011873e-01,-2.032439e-01,-9.227827e-01,-8.591595e-01,0.000000
50%,-2.897467e-01,-3.336174e-03,4.814115e-01,6.657725e-03,-1.442272e-02,1.876644e-02,4.055118e-01,-1.047172e-01,-2.032439e-01,-1.062677e-01,-1.306416e-03,1.000000
75%,3.917374e-01,8.646348e-01,4.814115e-01,8.525217e-01,1.189129e+00,8.027453e-01,1.273185e+00,5.953064e-01,-2.032439e-01,6.557115e-01,8.758243e-01,2.000000
max,5.571004e+00,1.691323e+00,2.770244e+00,1.738665e+00,2.392680e+00,1.978714e+00,2.140859e+00,2.567454e+00,6.628010e+00,2.536099e+00,1.724039e+00,3.000000

## Data Cleaning & Preprocessing
Langkah-langkah berikut melakukan pembersihan dan pra-pemrosesan data sesuai kriteria.

In [66]:
# Mengecek missing value dan data duplikat
print('Jumlah missing value tiap kolom:')
print(df.isnull().sum())
print('\nJumlah data duplikat:', df.duplicated().sum())

Jumlah missing value tiap kolom:
TransactionAmount          0
PreviousTransactionDate    0
TransactionType            0
Location                   0
Channel                    0
CustomerAge                0
CustomerOccupation         0
TransactionDuration        0
LoginAttempts              0
AccountBalance             0
TransactionDate            0
Target                     0
dtype: int64

Jumlah data duplikat: 22

In [67]:
# Menghapus kolom ID jika ada
id_cols = ['TransactionID', 'AccountID', 'DeviceID', 'IPAddress', 'MerchantID']
df = df.drop([col for col in id_cols if col in df.columns], axis=1)

In [68]:
# Feature encoding untuk kolom kategorikal
from sklearn.preprocessing import LabelEncoder
categorical_cols = df.select_dtypes(include=['object', 'category']).columns
for col in categorical_cols:
    df[col] = LabelEncoder().fit_transform(df[col].astype(str))

In [69]:
# Feature scaling untuk kolom numerik
from sklearn.preprocessing import StandardScaler
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns
df[numerical_cols] = StandardScaler().fit_transform(df[numerical_cols])

In [70]:
# Investigasi y_train setelah split
print('Tipe y_train:', y_train.dtype)
print('Nilai unik y_train:', y_train.unique())
print('Apakah ada NaN di y_train?', y_train.isnull().any())
print('Apakah semua integer?', all(y_train == y_train.astype(int)))
print('Apakah semua nilai diskrit?', set(y_train) == set(y_train.astype(int)))
print('Contoh 10 nilai y_train:', y_train.head(10).tolist())

Tipe y_train: int64
Nilai unik y_train: [1 0 2 3]
Apakah ada NaN di y_train? False
Apakah semua integer? True
Apakah semua nilai diskrit? True
Contoh 10 nilai y_train: [1, 0, 2, 0, 3, 2, 3, 0, 2, 2]

In [71]:
# Cek type dan shape y_train dan y_test
print('type y_train:', type(y_train))
print('shape y_train:', y_train.shape)
print('type y_test:', type(y_test))
print('shape y_test:', y_test.shape)

type y_train: <class 'pandas.core.series.Series'>
shape y_train: (1936,)
type y_test: <class 'pandas.core.series.Series'>
shape y_test: (484,)

In [72]:
# Paksa y_train dan y_test menjadi integer 1D array
import numpy as np
y_train_fixed = y_train.astype(int).values.ravel()
y_test_fixed = y_test.astype(int).values.ravel()
print('type y_train_fixed:', type(y_train_fixed), 'shape:', y_train_fixed.shape)
print('type y_test_fixed:', type(y_test_fixed), 'shape:', y_test_fixed.shape)
print('unique y_train_fixed:', np.unique(y_train_fixed))

# Training ulang DecisionTreeClassifier
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train_fixed)
print('Training DecisionTreeClassifier berhasil!')

type y_train_fixed: <class 'numpy.ndarray'> shape: (1936,)
type y_test_fixed: <class 'numpy.ndarray'> shape: (484,)
unique y_train_fixed: [0 1 2 3]
Training DecisionTreeClassifier berhasil!

## Membangun Model Klasifikasi: Decision Tree
Langkah-langkah berikut membangun model klasifikasi Decision Tree dan menyimpan model.

In [73]:
# Membagi dataset menjadi data latih dan data uji
from sklearn.model_selection import train_test_split
X = df.drop('Target', axis=1) if 'Target' in df.columns else df.iloc[:,:-1]
y = df['Target'] if 'Target' in df.columns else df.iloc[:,-1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [74]:
# Membangun dan melatih model Decision Tree
from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train_fixed)

DecisionTreeClassifier(random_state=42)

In [75]:
# Menyimpan model Decision Tree ke file decision_tree_model.h5
import joblib
joblib.dump(dt_model, 'decision_tree_model.h5')
print('Model Decision Tree berhasil disimpan ke decision_tree_model.h5')

Model Decision Tree berhasil disimpan ke decision_tree_model.h5

In [76]:
# Menyimpan model Decision Tree agar dapat dinilai reviewer
import joblib
joblib.dump(dt_model, 'decision_tree_model.h5')

['decision_tree_model.h5']

In [77]:
# Pastikan kolom Target bertipe integer (diskrit) sebelum train_test_split
if 'Target' in df.columns:
    df['Target'] = df['Target'].round().astype(int)

In [78]:
# Menambahkan label hasil clustering ke df jika belum ada
import pandas as pd
if 'Target' not in df.columns:
    df_target = pd.read_csv('data_clustering_with_target.csv')
    if 'Target' in df_target.columns:
        df['Target'] = df_target['Target']
        df['Target'] = df['Target'].round().astype(int)

### Penjelasan Analisis EDA

**Metode yang digunakan:**
Menampilkan data dengan head(), info(), dan describe() untuk memahami struktur dan ringkasan statistik dataset.

**Alasan penggunaan:**
EDA penting untuk mengetahui tipe data, distribusi, dan potensi masalah pada data sebelum pemodelan.

**Hasil yang didapat:**
Diperoleh gambaran awal mengenai jumlah data, tipe fitur, dan statistik dasar yang membantu proses preprocessing dan pemodelan selanjutnya.

### Penjelasan Analisis Preprocessing

**Metode yang digunakan:**
Pengecekan missing value, duplikat, drop kolom ID, encoding LabelEncoder, dan scaling MinMaxScaler.

**Alasan penggunaan:**
Preprocessing diperlukan agar data bersih, siap digunakan, dan seluruh fitur numerik/kategorikal dapat diproses algoritma machine learning.

**Hasil yang didapat:**
Data sudah bebas missing value, duplikat, dan seluruh fitur sudah dalam format numerik terstandardisasi.

### Penjelasan Analisis Klasifikasi

**Metode yang digunakan:**
train_test_split, Decision Tree Classifier, dan evaluasi model.

**Alasan penggunaan:**
Decision Tree mudah diinterpretasi dan cocok untuk data tabular, serta train_test_split memastikan evaluasi model yang adil.

**Hasil yang didapat:**
Model Decision Tree berhasil dilatih dan dievaluasi, serta model disimpan untuk penilaian otomatis.